name: Bump Version

on:
  workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Tag
        uses: ./.github/actions/tag@v2.2.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
